---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor

metadata:
  name: arc-systems-controller
  namespace: arc-systems

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gha-rs-controller
      app.kubernetes.io/component: controller-manager

  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      relabelings:
        - sourceLabels: [__address__]
          targetLabel: job
          replacement: arc-controller

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor

metadata:
  name: arc-systems-listener
  namespace: arc-systems

spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: gha-runner-scale-set
      app.kubernetes.io/component: runner-scale-set-listener

  podMetricsEndpoints:
    - targetPort: 8080
      path: /metrics
      interval: 30s
      relabelings:
        - sourceLabels: [__address__]
          targetLabel: job
          replacement: arc-listeners
        - sourceLabels: [name]
          targetLabel: runner_scale_set_name
          replacement: $1
