---
githubConfigUrl: "https://github.com/NullMonkeys"
githubConfigSecret: nullmonkeys-arc-runner-set-secrets

minRunners: 0
maxRunners: 2

containerMode:
  type: "dind"

controllerServiceAccount:
  namespace: arc-systems
  name: arc-systems-gha-rs-controller
