---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret

metadata:
  name: nullmonkeys-arc-runner-set-secrets-sync
  namespace: nullmonkeys-arc-runner-set

spec:
  infisicalAuthRef:
    name: cluster-wide-auth
    namespace: infisical-operator-system

  syncOptions:
    refreshInterval: 1h
    instantUpdates: false

  sources:
    - projectId: "acbf89d5-1845-4cbe-9e2d-e623806693e8"
      environmentSlug: "prod"
      secretPath: "/k3s/nullmonkeys-arc-runner-set"

  targets:
    - name: nullmonkeys-arc-runner-set-secrets
      namespace: nullmonkeys-arc-runner-set
      kind: Secret
      creationPolicy: Owner
