---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ezbookkeeping-s3.yaml
  - ezbookkeeping-secrets.yaml
  - ezbookkeeping-deployment.yaml
  - ezbookkeeping-service.yaml
  - ezbookkeeping-ingress.yaml
  - postgres-cluster.yaml

patches:
  - path: postgres-patch-init.yaml
  # - path: postgres-patch-recovery.yaml
