---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster

metadata:
  name: ezbookkeeping-db
  namespace: ezbookkeeping

spec:
  bootstrap:
    recovery:
      source: ezbookkeeping-db
      database: ezbookkeeping
      owner: ezbookkeeping

  externalClusters:
    - name: ezbookkeeping-db
      barmanObjectStore:
        destinationPath: s3://ezbookkeeping-backups
        endpointURL: https://451fb6a669f1b3cb2ac4fdbfce4a2201.r2.cloudflarestorage.com

        s3Credentials:
          accessKeyId:
            name: ezbookkeeping-secrets
            key: cloudflare-r2-access-key
          secretAccessKey:
            name: ezbookkeeping-secrets
            key: cloudflare-r2-secret-key

        wal:
          compression: gzip
          maxParallel: 8
