---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nextcloud

resources:
  - nextcloud-s3.yaml
  - nextcloud-secrets.yaml
  - postgres-cluster.yaml
  - traefik-middleware.yaml

patches:
  - path: postgres-patch-init.yaml
  # - path: postgres-patch-recovery.yaml

helmCharts:
  - name: nextcloud
    repo: https://nextcloud.github.io/helm/
    version: 9.2.6
    releaseName: nextcloud
    namespace: nextcloud
    valuesFile: nextcloud-values.yaml

  - name: redis
    repo: https://charts.bitnami.com/bitnami
    version: 28.3.1
    releaseName: redis
    namespace: nextcloud
    valuesFile: redis-values.yaml
