---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster

metadata:
  name: nextcloud-db
  namespace: nextcloud

spec:
  bootstrap:
    recovery:
      source: nextcloud-db
      database: nextcloud
      owner: nextcloud

  externalClusters:
    - name: nextcloud-db
      barmanObjectStore:
        destinationPath: s3://nextcloud-backups
        endpointURL: https://451fb6a669f1b3cb2ac4fdbfce4a2201.r2.cloudflarestorage.com

        s3Credentials:
          accessKeyId:
            name: nextcloud-secrets
            key: cloudflare-r2-access-key
          secretAccessKey:
            name: nextcloud-secrets
            key: cloudflare-r2-secret-key

        wal:
          compression: gzip
          maxParallel: 8
