---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret

metadata:
  name: librechat-secrets-sync
  namespace: librechat

spec:
  infisicalAuthRef:
    name: cluster-wide-auth
    namespace: infisical-operator-system

  syncOptions:
    refreshInterval: 1h
    instantUpdates: false

  sources:
    - projectId: "acbf89d5-1845-4cbe-9e2d-e623806693e8"
      environmentSlug: "prod"
      secretPath: "/k3s/librechat"

  targets:
    - name: librechat-secrets
      namespace: librechat
      kind: Secret
      creationPolicy: Owner
