---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: poznote-data
  namespace: poznote
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job.longhorn.io/nightly-backup: enabled

spec:
  storageClassName: longhorn

  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 5Gi
