---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster

metadata:
  name: test-task-todo-db
  namespace: test-task-todo

spec:
  instances: 1

  monitoring:
    enablePodMonitor: true

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname

  storage:
    size: 2Gi
    storageClass: longhorn
