---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: test-task-todo
  namespace: test-task-todo

spec:
  replicas: 1

  selector:
    matchLabels:
      app: test-task-todo

  template:
    metadata:
      labels:
        app: test-task-todo

    spec:
      enableServiceLinks: false
      initContainers:
        - name: migrate
          image: ghcr.io/magicman517/test-task-todo:0.0.1
          imagePullPolicy: IfNotPresent
          args:
            - --migrate

          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: test-task-todo-db-app
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: test-task-todo-db-app
                  key: port
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: test-task-todo-db-app
                  key: dbname
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: test-task-todo-db-app
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: test-task-todo-db-app
                  key: password
            - name: ConnectionStrings__database
              value: "Host=$(DB_HOST);Port=$(DB_PORT);Database=$(DB_NAME);Username=$(DB_USERNAME);Password=$(DB_PASSWORD);GSS Encryption Mode=Disable"

      containers:
        - name: test-task-todo
          image: ghcr.io/magicman517/test-task-todo:0.0.1
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080
              name: http

          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: test-task-todo-db-app
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: test-task-todo-db-app
                  key: port
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: test-task-todo-db-app
                  key: dbname
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: test-task-todo-db-app
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: test-task-todo-db-app
                  key: password
            - name: ConnectionStrings__database
              value: "Host=$(DB_HOST);Port=$(DB_PORT);Database=$(DB_NAME);Username=$(DB_USERNAME);Password=$(DB_PASSWORD);GSS Encryption Mode=Disable"
