---
global:
  env:
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: authentik-secrets
          key: secret-key

    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-db-app
          key: password

    - name: AUTHENTIK_POSTGRESQL__READ_REPLICAS__0__HOST
      value: "authentik-db-ro"
    - name: AUTHENTIK_POSTGRESQL__READ_REPLICAS__0__NAME
      value: "authentik"
    - name: AUTHENTIK_POSTGRESQL__READ_REPLICAS__0__USER
      value: "authentik"
    - name: AUTHENTIK_POSTGRESQL__READ_REPLICAS__0__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-db-app
          key: password

    - name: AUTHENTIK_STORAGE__BACKEND
      value: "s3"
    - name: AUTHENTIK_STORAGE__S3__ENDPOINT
      value: "https://451fb6a669f1b3cb2ac4fdbfce4a2201.r2.cloudflarestorage.com"
    - name: AUTHENTIK_STORAGE__S3__CUSTOM_DOMAIN
      value: "authentik-media.nullmonkeys.com"
    - name: AUTHENTIK_STORAGE__S3__BUCKET_NAME
      value: "authentik-media"
    - name: AUTHENTIK_STORAGE__S3__ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: authentik-secrets
          key: cloudflare-r2-access-key
    - name: AUTHENTIK_STORAGE__S3__SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: authentik-secrets
          key: cloudflare-r2-secret-key

    - name: AUTHENTIK_EMAIL__USERNAME
      valueFrom:
        secretKeyRef:
          name: authentik-secrets
          key: smtp-username
    - name: AUTHENTIK_EMAIL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-secrets
          key: smtp-password

authentik:
  enabled: true

  postgresql:
    host: "authentik-db-rw"
    name: "authentik"
    user: "authentik"

  email:
    host: "smtp.resend.com"
    port: 587
    use_tls: true
    from: "auth@nullmonkeys.com"

postgresql:
  enabled: false

server:
  enabled: true
  replicas: 2

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  ingress:
    enabled: true
    ingressClassName: traefik

    annotations:
      cert-manager.io/cluster-issuer: infisical-acme

    hosts:
      - auth.nullmonkeys.com

    tls:
      - hosts:
          - auth.nullmonkeys.com
        secretName: authentik-tls

worker:
  enabled: true
  replicas: 2

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
