---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mariadb-operator

helmCharts:
  - name: mariadb-operator
    repo: https://mariadb-operator.github.io/mariadb-operator
    version: 26.10.0
    releaseName: mariadb-operator
    namespace: mariadb-operator
    valuesFile: values.yaml

  - name: mariadb-operator-crds
    repo: https://mariadb-operator.github.io/mariadb-operator
    version: 26.10.0
    releaseName: mariadb-operator-crds
    namespace: mariadb-operator
