---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pelican-panel

resources:
  - pelican-deployment.yaml
  - pelican-ingress.yaml
  - pelican-pvc.yaml
  - pelican-secrets.yaml
  - pelican-svc.yaml
  - postgres-cluster.yaml
  - postgres-backup.yaml

patches:
  - path: postgres-patch-init.yaml
  # - path: postgres-patch-recovery.yaml

helmCharts:
  - name: redis
    repo: https://charts.bitnami.com/bitnami
    version: 28.0.10
    releaseName: redis
    namespace: pelican-panel
    valuesFile: redis-values.yaml
