---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB

metadata:
  name: pelican-mariadb
  namespace: pelican-panel

spec:
  rootPasswordSecretKeyRef:
    name: pelican-panel-secrets
    key: mariadb-root-password

  storage:
    size: 5Gi
    storageClassName: longhorn

  replicas: 1

  service:
    type: LoadBalancer

  metrics:
    enabled: true

  resources:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      memory: 4Gi

  myCnf: |
    [mariadb]
    max_connections=500
    max_connect_errors=10000
    thread_cache_size=50
    table_open_cache=2000

  affinity:
    antiAffinityEnabled: true

  # tls:
  #   enabled: true
