---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pelican-panel-data-pvc
  namespace: pelican-panel
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pelican-panel-logs-pvc
  namespace: pelican-panel
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pelican-panel-plugins-pvc
  namespace: pelican-panel
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
