---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster

metadata:
  name: pelican-panel-db
  namespace: pelican-panel

spec:
  instances: 1

  monitoring:
    enablePodMonitor: true

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname

  storage:
    size: 5Gi
    storageClass: longhorn

  backup:
    retentionPolicy: "3d"

    barmanObjectStore:
      destinationPath: s3://pelican-panel-backups
      endpointURL: https://451fb6a669f1b3cb2ac4fdbfce4a2201.r2.cloudflarestorage.com

      s3Credentials:
        accessKeyId:
          name: pelican-panel-secrets
          key: cloudflare-r2-access-key
        secretAccessKey:
          name: pelican-panel-secrets
          key: cloudflare-r2-secret-key

      wal:
        compression: gzip
        maxParallel: 8
