---
architecture: replication

auth:
  enabled: false
  sentinel: false

master:
  persistence:
    enabled: true
    storageClass: "longhorn"
    size: 1Gi

replica:
  replicaCount: 1
  persistence:
    enabled: true
    storageClass: "longhorn"
    size: 1Gi
