---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer

metadata:
  name: infisical-acme
  annotations:
    argocd.argoproj.io/sync-wave: "2"

spec:
  acme:
    server: "https://app.infisical.com/api/v1/cert-manager/acme/applications/2abf26f1-619f-4cf0-8086-ff8750e9f94b/profiles/95a9f5fe-11a0-492b-a799-ab610f2aecf3/directory"
    email: no-reply@nullmonkeys.com

    privateKeySecretRef:
      name: infisical-acme-account

    externalAccountBinding:
      keyID: "319c7554-75f5-4d33-bb98-a7d4779ff260"
      keySecretRef:
        name: cert-manager-secrets
        key: eab-secret
      keyAlgorithm: HS256

    solvers:
      - selector:
          dnsZones:
            - "internal.nullmonkeys.com"
        dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secrets
              key: cloudflare-api-token

      - selector: {}
        http01:
          ingress:
            class: traefik
