---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret

metadata:
  name: cert-manager-secrets-sync
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  infisicalAuthRef:
    name: cluster-wide-auth
    namespace: infisical-operator-system

  syncOptions:
    refreshInterval: 1h
    instantUpdates: false

  sources:
    - projectId: "acbf89d5-1845-4cbe-9e2d-e623806693e8"
      environmentSlug: "prod"
      secretPath: "/k3s/cert-manager"

  targets:
    - name: cert-manager-secrets
      namespace: cert-manager
      kind: Secret
      creationPolicy: Owner
