---
defaultSettings:
  defaultDataPath: /var/lib/longhorn
  storageReservedPercentageForDefaultDisk: 5
  storageMinimalAvailablePercentage: 5

defaultBackupStore:
  backupTarget: "s3://longhorn-backups@auto/"
  backupTargetCredentialSecret: longhorn-system-secrets

persistence:
  defaultClassReplicaCount: 2

metrics:
  serviceMonitor:
    enabled: true

ingress:
  enabled: true
  ingressClassName: traefik
  host: longhorn.internal.nullmonkeys.com
  tls: true
  tlsSecret: longhorn-tls
  annotations:
    cert-manager.io/cluster-issuer: infisical-acme
