---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seaweedfs-admin-data
  namespace: seaweedfs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: seaweedfs-longhorn
  resources:
    requests:
      storage: 1Gi

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: seaweedfs-admin-authentik
  namespace: seaweedfs
spec:
  forwardAuth:
    address: http://authentik-server.authentik.svc.cluster.local:80/outpost.goauthentik.io/auth/traefik
    trustForwardHeader: true
    authResponseHeaders:
      - X-authentik-username
      - X-authentik-groups
      - X-authentik-email
      - X-authentik-name
      - X-authentik-uid

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seaweedfs-admin
  namespace: seaweedfs
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/router.middlewares: seaweedfs-seaweedfs-admin-authentik@kubernetescrd

spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - seaweedfs.internal.nullmonkeys.com
      secretName: seaweedfs-admin-tls
  rules:
    - host: seaweedfs.internal.nullmonkeys.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seaweedfs-admin
                port:
                  number: 23646

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: seaweedfs-admin
  namespace: seaweedfs
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: seaweedfs
      app.kubernetes.io/instance: seaweedfs
      app.kubernetes.io/component: admin
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
      ports:
        - protocol: TCP
          port: 23646
