---
apiVersion: seaweed.seaweedfs.com/v1
kind: ResourceReferenceGrant

metadata:
  name: nextcloud-s3
  namespace: seaweedfs
  annotations:
    argocd.argoproj.io/sync-wave: "10"

spec:
  from:
    - group: seaweed.seaweedfs.com
      kind: S3Identity
      namespace: nextcloud
    - group: seaweed.seaweedfs.com
      kind: S3Credentials
      namespace: nextcloud
  to:
    - group: seaweed.seaweedfs.com
      kind: Seaweed
      name: seaweedfs
