---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: searxng

resources:
  - searxng-secrets.yaml
  - searxng-config.yaml
  - searxng-limiter.yaml
  - searxng-svc.yaml
  - searxng-ingress.yaml
  - searxng-deployment.yaml

helmCharts:
  - name: valkey
    repo: oci://registry-1.docker.io/bitnamicharts
    version: 6.2.8
    releaseName: valkey
    namespace: searxng
    valuesFile: valkey-values.yaml
