---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: searxng

resources:
  - secrets.yaml
  - config.yaml
  - limiter.yaml
  - service.yaml
  - ingress.yaml
  - deployment.yaml

helmCharts:
  - name: valkey
    repo: oci://registry-1.docker.io/bitnamicharts
    version: 6.2.2
    releaseName: valkey
    namespace: searxng
    valuesFile: valkey-values.yaml
